#!/bin/bash
set -e -x

# Get Storage connection string
STORAGE_CONNECTION_STRING=$(az storage account show-connection-string \
--resource-group $RESOURCE_GROUP --name $STORAGE_ACCOUNT_NAME \
--query connectionString --output tsv)

COSMOSDB_KEY=$(az cosmosdb list-keys --name $COSMOSDB_ACCOUNT_NAME --resource-group $RESOURCE_GROUP -o tsv |awk '{print $1}')

az webapp config appsettings set \
  -n $AZFUNC_APP_NAME \
  -g $RESOURCE_GROUP \
  --settings \
AzureWebJobsStorage=$STORAGE_CONNECTION_STRING \
FUNCTIONS_EXTENSION_VERSION=~2 \
FACEAPI_ENDPOINT=$FACEAPI_ENDPOINT \
FACEAPI_SUBKEY=$FACEAPI_SUBKEY \
COSMOSDB_ENDPOINT=https://$COSMOSDB_ACCOUNT_NAME.documents.azure.com:443/ \
COSMOSDB_KEY=$COSMOSDB_KEY \
COSMOSDB_DATABASE_NAME=$COSMOSDB_DATABASE_NAME \
COSMOSDB_ASSET_COLLECTION_NAME=$COSMOSDB_ASSET_COLLECTION_NAME \
COSMOSDB_USER_COLLECTION_NAME=$COSMOSDB_USER_COLLECTION_NAME \
COSMOSDB_PHOTO_COLLECTION_NAME=$COSMOSDB_PHOTO_COLLECTION_NAME
